#!/bin/bash
ARGUMENT=$1;
if [[ -f $ARGUMENT ]]; then
    # GET HERE IF FILE ARGUMENT IS VALID:
    # USE sed MAGIC TO DO THE WORK:
    # HERE WE ADD U+FEFF BYTE ORDER MARK TO THE BEGINNING OF THE FILE
    # The following sed command line adds the individual UTF-8 bytes:
    #sed -i .bak '1s/^/\xef\xbb\xbf/' $ARGUMENT
    # The following is functionally equivalent to the above
    # but contains the UTF-8 U+FEFF BOM character directly:
    sed -E -i.original '1s/^/﻿/' $ARGUMENT
else
    echo "ADD_BOM is (c) 2019, 2022 by Edward H. Trager."
    echo ""
    echo "add_bom adds a Unicode byte order mark BOM to the beginning of a file."
    echo "Microsoft Excel very curiously requires this in order to treat a file as UTF-8."
    echo ""
    echo "The contents of the original file are preserved in a file with .original added"
    echo "to the end of the file name. The original file name will now contain a BOM"
    echo "at the beginning of the file."
    echo ""
    echo "Please pass a valid file name as the command line argument."
    exit 1
fi

